@startuml
package LAN {
    package Examinees {
        [OpenBox1] -- "getScreenshot  "
        [OpenBox2] -- "getScreenshot"
        [OpenBox3] -- "getScreenshot "
    }

    node Instructors {
        [Frontend]
    }

    node Recorder
}

cloud {
    [Server] -left- "examinee" : "                           "
    [Server] -right- "getExaminees"  : "                           "
}

[OpenBox1] -up-> "examinee" : "via websocket"
[OpenBox2] -up-> "examinee"
[OpenBox3] -up-> "examinee"

[Frontend] -left-> "getExaminees"
[Frontend] -left-> "getScreenshot  " : "low quality       "

Recorder --> "getExaminees"
Recorder -down-> "getScreenshot  " : "high quality"
@enduml