= Franklyn
Aichinger Tobias, Cvijić Luka, Schludermann Julian, Schnalzenberger Arwed
:icons: font
:sectnums:
:toc: left

== Description

Franklyn is an application that provides students with a professional working environment during assessments.

Teachers will be given the opportunity to create test sessions. Students can log in to a session with a PIN or by first and last name. The student client takes screenshots at regular intervals, which the teacher can view.


== UCD
image::http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/2324-4bhif-syp/2324-4bhif-syp-project-franklyn/main/plantuml/franklyn-ucd.puml[]


== Team Members

* Aichinger Tobias
* Cvijić Luka
* Schludermann Julian
* Schnalzenberger Arwed

== Getting started

=== Server

* Open the "client"-folder in a terminal and type this command:

.start command
[source, bash]
----
./mvnw clean quarkus:dev
----

* Now open the site http://localhost:8080/ in your browser. Now you should be able to see a new image every time you reload the page.

