= Franklyn
Aichinger Tobias, Cvijić Luka, Schludermann Julian, Schnalzenberger Arwed
:icons: font
:sectnums:
:toc: left

== Description

Franklyn is an application that provides students with a professional working environment during assessments.

Teachers will be given the opportunity to create test sessions. Students can log in to a session with a PIN or by first and last name. The student client takes screenshots at regular intervals, which the teacher can view.

== UCD
image::http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/2324-4bhif-syp/2324-4bhif-syp-project-franklyn/main/asciidocs/docs/plantuml/franklyn-ucd.puml[]

== Team Members

* Aichinger Tobias
* Cvijić Luka
* Schludermann Julian
* Schnalzenberger Arwed

== Slides
Revealjs Slides can be found https://2324-4bhif-syp.github.io/2324-4bhif-syp-project-franklyn/slides[here]

== For developers
=== Subprojects
* *openbox*: application running on the students' computer. Connected with a WebSocket connection to the *server*. Provides a REST interface for gathering Data (e.g. screenshots)
* *server*: application managing *boxes*. meaning: storing username, ipaddress and connection states (connected, disconnected) and providing an REST Endpoint for other applications to get this data.
* *recorder*: application periodically fetching high quality screenshots from active *boxes* and persisting them.
* *instructor-client*: frontend displaying information (connection state, screenshot, ...) about *boxes* (students) to the examiner/instructor.

=== Getting started: an example

In the property-files one can set different values for the application.

For example one can set the application port for the quarkus applications (Server, Recorder, Openbox).

==== Server

.start the server
[source, bash]
----
./mvnw clean quarkus:dev
----

link:./server/src/main/resources/application.properties[Properties]

==== Instructor-client

.start the angular instructor frontend
[source, bash]
----
ng serve --open <.>
----
<.> "--open" directly opens the website after it finished loading

link:./instructor-client/src/environment/environment.ts[Properties]

==== Openbox (Student client)

.start the openbox
[source, bash]
----
./mvnw clean quarkus:dev
----

link:./openbox/src/main/resources/application.properties[Properties]
