services:
  franklyn-server:
    container_name: franklyn-server
    image: ghcr.io/2324-4bhif-syp/2324-4bhif-syp-project-franklyn/franklyn-server:dev
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /opt/docker/franklyn/screenshots:/var/lib/franklyn/screenshots
    networks:
      - franklyn-net

  franklyn-instructor-client:
    container_name: franklyn-instructor-client
    image: ghcr.io/2324-4bhif-syp/2324-4bhif-syp-project-franklyn/franklyn-instructor-client:dev
    restart: unless-stopped
    depends_on:
      - franklyn-server
    ports:
      - 8088:80
    networks:
      - franklyn-net

  franklyn-db:
    container_name: franklyn-db
    image: postgres:17.0-alpine3.20
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - /var/lib/franklyn/db:/var/lib/postgresql/data
      - /var/lib/franklyn/db-import:/import
    networks:
      - franklyn-net
networks:
  franklyn-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
