### POST IPv4 Adress
POST http://localhost:8080/connection
Content-Type: application/json

{
  "ip-adress": "22.172.233.37"
}

### POST IPv4 Adress but use wrong name
POST http://localhost:8080/connection
Content-Type: application/json

{
  "my-ip-adress": "22.172.233.37"
}

### POST IPv4 Adress but use wrong values
POST http://localhost:8080/connection
Content-Type: application/json

{
  "ip-adress": "15.172.256.37"
}

