### Create new Exam
POST http://localhost:8080/exams
Content-Type: application/json

{
  "title": "WMC Test02",
  "start": "2030-03-18T12:20:00",
  "end": "2030-03-18T16:30:00"
}

### Get Exam by id
GET http://localhost:8080/exams/1
Accept: application/json

### Get all exams
GET http://localhost:8080/exams
Accept: application/json

### Delete exam by id
DELETE http://localhost:8080/exams/1
Accept: application/json

### Get examinees of exam
GET http://localhost:8080/exams/1/examinees
Accept: application/json

### Join Exam
POST http://localhost:8080/exams/join/416
Content-Type: application/json

{
  "firstname": "Franz",
  "lastname": "Höller"
}





### GET all examinees
GET http://localhost:8080/examinees

### Reset state (delte screenshot folder, clear examinees)
POST http://localhost:8080/state/reset

### Get System metrics
GET http://localhost:8080/state/system-metrics
Content-Type: */*