### GET all examinees
GET http://localhost:8080/examinees

### Reset state (delte screenshot folder, clear examinees)
POST http://localhost:8080/state/reset

### Get System metrics
GET http://localhost:8080/state/system-metrics
Content-Type: */*