@startuml
left to right direction

cloud INET {
    rectangle " " #line:transparent {
        () uploadScreenshot
        () "getExaminees"
        () "getScreenshot"
        () "downloadVideo"
    }

    "uploadScreenshot" -- [Server]
    "getExaminees" -- [Server]
    "getScreenshot" -- [Server]
    "downloadVideo" -- [Server]
}

package LAN {
    package Examinees {
        [OpenBox1] -- "uploadScreenshot"
        [OpenBox2] -- "uploadScreenshot"
        [OpenBox3] -- "uploadScreenshot"
    }

    node Instructors {
        [Frontend] <<browser>>
    }
}
[Frontend] -- "getExaminees"
[Frontend] -- "getScreenshot"
[Frontend] -- "downloadVideo"

" " -[hidden]- INET
LAN -[hidden]- " "
@enduml
