@startuml
left to right direction

actor "Instructor" as in
actor "Examine" as ex

rectangle "Franklyn" {
  usecase "Create a session" as UC1
  usecase "Observe displays of the examines" as UC2
  usecase "Download the last session" as UC3
  usecase "Subscribe to a session" as UC4
}

in -- UC1
in -- UC2
in -- UC3
ex -- UC4
@enduml