name: Build Openbox

on:
  push:
    paths:
      - 'openbox/**'
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  build-openbox:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'openbox/pom.xml'

      - name: Build with maven
        run: |
          ./cicd/build-openbox.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'student-client'
          path: 'dist/openbox/franklyn-student-client.jar'