name: Build and Deploy Dockerfiles
run-name: ${{ github.actor }} is building Docker images 🚀
on:
  push:
    branches:
      - main
      - develop
      - feat/docker-ci
  workflow_dispatch:
jobs:
  build-images:
    permissions: write-all
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Find and set image tag
        run: |
          - if test "${{ github.ref_name }}" = "main"; then tag="latest"; else tag="dev"; fi
          - echo "IMAGE_TAG=${tag}" >> "$GITHUB_ENV"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/src/main/docker/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/franklyn-server:$IMAGE_TAG
