name: Build Openbox

on:
  push:
    paths:
      - 'openbox/**'
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:


jobs:
  build-openbox:
    runs-on: ubuntu-22.04
    steps:
      - uses: hecrj/setup-rust-action@v2
      - name: Install cargo-deb
        run: cargo install cargo-deb
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTED=noninteractive
          sudo apt-get -qq update
          sudo apt-get install -y libxkbcommon-dev
      - name: Build openbox binary
        run: |
          cd openbox
          cargo build --profile release-opt --package openbox
      - name: Archive openbox binary
        uses: actions/upload-artifact@v4
        with:
          name: openbox-x86_64-unknown-linux-gnu
          path: openbox/target/release-opt/openbox
      - name: Pack openbox .deb package
        run: |
          cd openbox
          cargo deb --no-build --profile release-opt --package openbox
      - name: Rename openbox .deb package
        run: mv openbox/target/debian/*.deb openbox/target/debian/openbox-x86_64-debian-linux-gnu.deb
      - name: Archive openbox .deb package
        uses: actions/upload-artifact@v4
        with:
          name: openbox-x86_64-debian-linux-gnu
          path: openbox/target/debian/openbox-x86_64-debian-linux-gnu.deb

  openbox_macos:
    runs-on: macOS-12
    steps:
    - uses: hecrj/setup-rust-action@v2
    - uses: actions/checkout@master
    - name: Build openbox binary
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.14
      run: |
        cd openbox
        cargo build --profile release-opt --package openbox
    - name: Open binary via double-click
      run: chmod +x openbox/target/release-opt/openbox
    - name: Archive openbox binary
      uses: actions/upload-artifact@v1
      with:
        name: openbox-x86_64-apple-darwin
        path: openbox/target/release-opt/openbox
