name: Build and deploy

on:
  push:
    branches:
      - develop
      - main
      - rc/3.1
    paths:
      - '.github/workflows/build-and-deploy.yaml'
      - '.github/workflows/build-docker.yaml'
      - 'cicd/**'
      - 'instructor-client/**'
      - 'nginx/**'
      - 'openbox/**'
      - 'server/**'
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  openbox-determine-version:
    runs-on: ubuntu-22.04
    steps:
      - id: identify
        run: |
          if test "${{ github.ref_name }}" = "main"; then 
            export feat="srv_prod"; 
          elif test "${{ github.ref_name }}" = "develop"; then 
            export feat="srv_ci";
          elif echo "${{ github.ref_name }}" | grep -q "^release/"; then
            export feat="srv_prod";
          elif echo "${{ github.ref_name }}" | grep -q "^rc/"; then
            export feat="srv_staging";
          else 
            export feat="default";
          fi
          echo "openbox_feature=${feat}" >> $GITHUB_OUTPUT
    outputs:
      openbox_feature: ${{ steps.identify.outputs.openbox_feature }}

  openbox-linux:
    needs: openbox-determine-version
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTED=noninteractive
          sudo apt-get -qq update
          sudo apt-get install -y wget git
      - name: Build openbox binary
        run: |
          cd openbox
          ./release-scripts/build.sh "${{ needs.openbox-determine-version.outputs.openbox_feature }}"
      - name: Archive openbox binary
        uses: actions/upload-artifact@v4
        with:
          name: openbox-x86_64-unknown-linux-gnu
          path: openbox/target/release-opt/openbox

  openbox-macos:
    needs: openbox-determine-version
    runs-on: macOS-15
    steps:
    - uses: hecrj/setup-rust-action@v2
    - uses: actions/checkout@master
    - name: Build openbox binary
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.14
      run: |
        cd openbox
        cargo build --profile release-opt --package openbox --features "${{ needs.openbox-determine-version.outputs.openbox_feature }}"
    - name: Open binary via double-click
      run: chmod +x openbox/target/release-opt/openbox
    - name: Archive openbox binary
      uses: actions/upload-artifact@v4
      with:
        name: openbox-x86_64-apple-darwin
        path: openbox/target/release-opt/openbox

  openbox-windows:
    needs: openbox-determine-version
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@master
      - uses: hecrj/setup-rust-action@v2
      - name: Add target for Windows
        run: rustup target add x86_64-pc-windows-msvc
      - name: Build openbox binary
        run: |
          cd openbox
          cargo build --profile release-opt --package openbox --target x86_64-pc-windows-msvc --features "${{ needs.openbox-determine-version.outputs.openbox_feature }}"
      - name: Archive openbox binary
        uses: actions/upload-artifact@v4
        with:
          name: openbox-x86_64-pc-windows-msvc
          path: openbox/target/x86_64-pc-windows-msvc/release-opt/openbox.exe

  app-docker-images:
    if: github.ref == 'refs/heads/develop'
    name: Build Docker images
    uses: ./.github/workflows/build-docker.yaml

  deploy-to-oravm:
    concurrency:
      group: deploy-to-oravm-group
      cancel-in-progress: true
    needs: [openbox-linux, openbox-macos, openbox-windows, app-docker-images]
    if: github.ref == 'refs/heads/develop'
    name: Deploy Franklyn
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup ssh
        run: source ./cicd/setup-ssh.sh ${{github.workspace}} ${{secrets.SSH_USERNAME}} ${{secrets.SSH_HOST}}
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}

      - name: Download openbox artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: openbox-*
          path: /tmp/openbox-artifacts/

      - name: Rename artifacts
        run: |
          mv /tmp/openbox-artifacts/openbox-x86_64-apple-darwin/openbox /tmp/openbox-artifacts/openbox-darwin
          rmdir /tmp/openbox-artifacts/openbox-x86_64-apple-darwin
          mv /tmp/openbox-artifacts/openbox-x86_64-unknown-linux-gnu/openbox /tmp/openbox-artifacts/openbox-linux
          rmdir /tmp/openbox-artifacts/openbox-x86_64-unknown-linux-gnu
          mv /tmp/openbox-artifacts/openbox-x86_64-pc-windows-msvc/openbox.exe /tmp/openbox-artifacts/openbox-windows.exe
          rmdir /tmp/openbox-artifacts/openbox-x86_64-pc-windows-msvc

      - name: Deploy build
        run: |
          ssh -i $SSH_KEY_PATH $SSH_USER@$SSH_HOST "git -C project-franklyn pull --rebase --autostash || git clone https://github.com/2324-4bhif-syp/2324-4bhif-syp-project-franklyn.git project-franklyn"
          ssh -i $SSH_KEY_PATH $SSH_USER@$SSH_HOST "git -C project-franklyn reset --hard"
          ssh -i $SSH_KEY_PATH $SSH_USER@$SSH_HOST "git -C project-franklyn clean -fd"
          ssh -i $SSH_KEY_PATH $SSH_USER@$SSH_HOST "git -C project-franklyn switch ${{ github.ref_name }}"
          ssh -i $SSH_KEY_PATH $SSH_USER@$SSH_HOST "git -C project-franklyn pull --rebase --autostash"
          ssh -i $SSH_KEY_PATH $SSH_USER@$SSH_HOST "docker compose -f project-franklyn/cicd/docker-compose.yaml down"
          ssh -i $SSH_KEY_PATH $SSH_USER@$SSH_HOST "echo 'IMAGE_TAG=dev' > project-franklyn/cicd/.env"
          ssh -i $SSH_KEY_PATH $SSH_USER@$SSH_HOST "docker compose -f project-franklyn/cicd/docker-compose.yaml pull"
          ssh -i $SSH_KEY_PATH $SSH_USER@$SSH_HOST "sudo cp -f project-franklyn/cicd/daemon.json /etc/docker/daemon.json"
          ssh -i $SSH_KEY_PATH $SSH_USER@$SSH_HOST "sudo systemctl restart docker.service"
          ssh -i $SSH_KEY_PATH $SSH_USER@$SSH_HOST "docker compose -f project-franklyn/cicd/docker-compose.yaml up -d"
          ssh -i $SSH_KEY_PATH $SSH_USER@$SSH_HOST "sudo cp -f project-franklyn/nginx/nginx.conf /etc/nginx/nginx.conf"
          ssh -i $SSH_KEY_PATH $SSH_USER@$SSH_HOST "sudo cp -f project-franklyn/nginx/index.html /var/www/html/"
          scp -i $SSH_KEY_PATH /tmp/openbox-artifacts/* $SSH_USER@$SSH_HOST:/var/www/downloads
          ssh -i $SSH_KEY_PATH $SSH_USER@$SSH_HOST "sudo systemctl restart nginx.service"
        shell: bash
