name: Build and release
run-name: ${{ github.actor }} is releasing the newest version.
on:
  push:
    branches: [main]
jobs:
  build-and-release-franklyn:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - run: java --version

      - name: Build with Maven
        run: |
          chmod +x ./cicd/build-openbox.sh
          ./cicd/build-openbox.sh
          chmod +x ./cicd/build-server.sh
          ./cicd/build-server.sh

      - name: Get the git commits since the last tag
        run: |
          git pull --unshallow
          echo "$(git log $(git describe --tags --abbrev=0)..HEAD | git shortlog)" | sed 's/^ \+/- /'  > release-notes.txt
          cat release-notes.txt

      - name: Release the build
        run: |
          tag="$(date +"%Y.%m.%d")-$(git rev-parse --short HEAD)"
          gh release create $tag ./dist/*/*.jar --title "franklyn $tag" --notes-file release-notes.txt --prerelease
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
