name: Deploy to oravm

concurrency: production # allow maximum of one running and pending job

on:
  push:
    paths:
      - 'server/**'
      - 'instructor-client/**'
    branches:
      - main
      - feat/cicd # TODO: remove
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy-frontend:
    name: Build and Deploy angular frontend
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.6.1'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: npm install, build
        run: ./cicd/build-instructor-client.sh

      - name: Setup ssh
        run: source ./cicd/setup-ssh.sh
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}

      - name: Deploy build
        run: |
          ssh -i $SSH_KEY_PATH $SSH_USER@$SSH_HOST "rm -f ~/www/*"
          scp -i $SSH_KEY_PATH instructor-client/dist/instructor-client/browser/* $SSH_USER@$SSH_HOST:~/www/
          ssh -i $SSH_KEY_PATH $SSH_USER@$SSH_HOST "sudo systemctl restart nginx"
        shell: bash